import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NowPlayingContextProvider } from "react-nowplaying";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-dvh">
      <body className={`h-full dark ${inter.className}`}>
        <NowPlayingContextProvider>{children}</NowPlayingContextProvider>
      </body>
    </html>
  );
}
